"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libsimple"
_LIBRARY_ENV_VAR = "LIBSIMPLE_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

# Forward declarations for recursive types
class CTree_Float64(ctypes.Structure):
    pass

class CVector_Float32(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_float)),
    ]

class CVectorPair_Float32(ctypes.Structure):
    _fields_ = [
        ("from_", CVector_Float32),
        ("to", CVector_Float32),
    ]

class MyTwoVec(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_int32),
        ("y", ctypes.c_int32),
    ]

class CVector_CTree_Float64(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int32),
        ("data", ctypes.POINTER(CTree_Float64)),
    ]

CTree_Float64._fields_ = [
    ("children", CVector_CTree_Float64),
]

_lib.tree_size.argtypes = [CTree_Float64]
_lib.tree_size.restype = ctypes.c_int64
def tree_size(tree):
    return _lib.tree_size(tree)

_lib.copyto_and_sum.argtypes = [CVectorPair_Float32]
_lib.copyto_and_sum.restype = ctypes.c_float
def copyto_and_sum(fromto):
    return _lib.copyto_and_sum(fromto)

_lib.countsame.argtypes = [ctypes.POINTER(MyTwoVec), ctypes.c_int32]
_lib.countsame.restype = ctypes.c_int32
def countsame(list, n):
    return _lib.countsame(list, n)

