"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libcstring"
_LIBRARY_ENV_VAR = "CSTRING_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

class CString(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    @classmethod
    def from_str(cls, s):
        """Return a CString whose buffer holds the UTF-8 encoding of `s`.

        Allocates a fresh ctypes buffer and copies the bytes into it; the
        returned object holds a reference to that buffer, so the caller
        must keep it alive for the duration of any C call that uses it."""
        if not isinstance(s, str):
            raise TypeError(f"expected str, got {type(s).__name__}")
        return cls.from_bytes(s.encode("utf-8"))

    @classmethod
    def from_bytes(cls, b):
        """Return a CString whose buffer holds a copy of the bytes `b`."""
        if not isinstance(b, (bytes, bytearray)):
            raise TypeError(f"expected bytes-like, got {type(b).__name__}")
        n = len(b)
        buf = (ctypes.c_uint8 * n).from_buffer_copy(b) if n else (ctypes.c_uint8 * 0)()
        obj = cls(length=n,
                  data=ctypes.cast(buf, ctypes.POINTER(ctypes.c_uint8)))
        obj._buffer = buf
        return obj

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        return self.as_bytes().decode("utf-8")

_lib.greeting_length.argtypes = [CString]
_lib.greeting_length.restype = ctypes.c_int32
def greeting_length(s):
    return _lib.greeting_length(s)

_lib.greeting.argtypes = []
_lib.greeting.restype = CString
def greeting():
    return _lib.greeting()

