"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib
import numpy as np

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libcmatrix"
_LIBRARY_ENV_VAR = "CMATRIX_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. Multiple "
        "JLW-wrapped libraries in one process is not a supported "
        "configuration: the dynamic linker silently shares a single "
        "libjulia across them, which assumes byte-compatible Julia "
        "versions and shares one Julia runtime. See the JuliaLibWrapping "
        "docs section on multiple wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

class CMatrix_Float64(ctypes.Structure):
    _fields_ = [
        ("rows", ctypes.c_int32),
        ("cols", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_double)),
    ]

    @classmethod
    def from_numpy(cls, arr):
        """Return a CMatrix view of the 2-D Fortran-contiguous numpy array `arr`.

        CMatrix storage is column-major (Julia / Fortran order). A default
        row-major (C-order) numpy array is REJECTED rather than silently
        transposed — call `np.asfortranarray(arr)` first if needed.
        Raises ValueError on ndim, contiguity, or dtype mismatch. The returned
        object holds a reference to `arr`, so the caller must keep it alive for
        the duration of any C call that uses the buffer."""
        if arr.ndim != 2:
            raise ValueError(f"expected 2-D array, got {arr.ndim}-D")
        if not arr.flags.f_contiguous:
            raise ValueError("array must be Fortran-contiguous (column-major); "
                             "use np.asfortranarray(arr) to convert")
        expected_dtype = np.dtype("float64")
        if arr.dtype != expected_dtype:
            raise ValueError(f"expected dtype float64, got {arr.dtype}")
        obj = cls(rows=arr.shape[0], cols=arr.shape[1],
                  data=arr.ctypes.data_as(ctypes.POINTER(ctypes.c_double)))
        obj._buffer = arr
        return obj

    def as_numpy(self):
        """Return a 2-D column-major numpy view of the underlying buffer (no copy).

        The view has shape `(rows, cols)` and Fortran (column-major) strides,
        matching the storage layout."""
        # Read the column-major buffer as (cols, rows) row-major then transpose:
        # the transpose is a view, and the result has the correct (rows, cols)
        # shape with column-major strides.
        return np.ctypeslib.as_array(self.data, shape=(self.cols, self.rows)).T

_lib.trace_cmatrix.argtypes = [CMatrix_Float64]
_lib.trace_cmatrix.restype = ctypes.c_double
def trace_cmatrix(m):
    return _lib.trace_cmatrix(m)

