"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "librawptr"
_LIBRARY_ENV_VAR = "RAWPTR_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. Multiple "
        "JLW-wrapped libraries in one process is not a supported "
        "configuration: the dynamic linker silently shares a single "
        "libjulia across them, which assumes byte-compatible Julia "
        "versions and shares one Julia runtime. See the JuliaLibWrapping "
        "docs section on multiple wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

_lib.sum_doubles.argtypes = [ctypes.POINTER(ctypes.c_double), ctypes.c_int64]
_lib.sum_doubles.restype = ctypes.c_double
def sum_doubles(data, n):
    """Raw pointer arguments — caller owns layout and lifetime.

    `data` is a raw pointer to Float64. The wrapper does not check length, shape, or memory order.

    Julia indexes multidimensional buffers column-major (Fortran order).
    A default numpy array is row-major (C order); passing `arr.ctypes.data`
    from such an array to a Julia function that interprets it as a matrix
    will see a silently transposed view. Use `np.asfortranarray(arr)` before
    taking `.ctypes.data`, or — better — wrap the field in `CVector{T}` /
    `CMatrix{T}` (JLWInterop) so length and layout travel with the buffer.
    """
    return _lib.sum_doubles(data, n)

