# host_blas support: compile the takeover into the wrapped library, prune the
# BLAS that `juliac` bundles anyway, and emit the Python import-time hook.
#
# A wrapped library that wants to run in the host's BLAS (typically the
# OpenBLAS that PyPI NumPy has already loaded) needs three things that used to
# be hand-written per project:
#
#   * the takeover module compiled into the same library, because two bundled
#     juliac libraries each carry their own libjulia and therefore their own
#     libblastrampoline;
#   * an import-time hook in the generated Python package that finds the host
#     BLAS and calls the takeover;
#   * the bundle prune that removes the bundled OpenBLAS and its gfortran/gomp
#     runtime, replacing the `libopenblas64_.so` slot with a non-BLAS stub so
#     that `OpenBLAS_jll`'s dlopen and libblastrampoline's interface probe
#     still succeed.
#
# Setting `host_blas = true` on a [`PythonTarget`](@ref) asks for all three.
# The host-BLAS search and the bundle prune are Linux-only: discovery reads
# `/proc/self/maps` and the prune replaces an ELF `.so`.

const _HOST_BLAS_DIR = joinpath(@__DIR__, "host_blas")
const _HOST_BLAS_TAKEOVER_PATH = joinpath(_HOST_BLAS_DIR, "HostBlasTakeover.jl")
const _HOST_BLAS_PLACEHOLDER_C = joinpath(_HOST_BLAS_DIR, "openblas_placeholder.c")

"""
    _HOST_BLAS_ENTRYPOINTS

The `Base.@ccallable` names the shipped takeover exports. They are build and
runtime plumbing, not the wrapped library's API: when `host_blas = true` the
generated façade and `__all__` omit them, while `_lowlevel` still binds them
so the emitted hook can call the takeover.
"""
const _HOST_BLAS_ENTRYPOINTS = (
    "hostblas_takeover", "hostblas_is_ready", "hostblas_last_error",
    "hostblas_forwarded_count",
)

"""
    _host_blas_setting(targets) -> Bool

Whether `targets` asks for a host-BLAS build, from the `host_blas` option on
its [`PythonTarget`](@ref)s. The takeover is compiled once per library, so
every Python target must agree; a mix is an error rather than a silent
choice. Targets of other languages do not carry the option and are ignored.
"""
function _host_blas_setting(targets::AbstractVector{<:AbstractTarget})
    values = Bool[t.host_blas for t in targets if t isa PythonTarget]
    isempty(values) && return false
    all(==(first(values)), values) || throw(
        ArgumentError(
            "every PythonTarget in one build must agree on `host_blas`: the " *
                "takeover is compiled into the shared library, so it cannot be " *
                "enabled for some targets and not others."
        )
    )
    return first(values)
end

"""
    _require_host_blas_supported()

Throw unless this host can run a `host_blas` build. Discovery reads
`/proc/self/maps`, and the bundle prune replaces an ELF `.so` and compiles the
placeholder with a C compiler, so the feature is Linux-only for now.
"""
function _require_host_blas_supported()
    Sys.islinux() || throw(
        ArgumentError(
            "host_blas = true is supported on Linux only: the generated hook " *
                "discovers the host BLAS through /proc/self/maps and the bundle " *
                "prune replaces an ELF OpenBLAS slot."
        )
    )
    # The takeover forwards symbols as `:ilp64`, and the placeholder claims the
    # `64_` suffix, so an LP64 Julia build cannot be retargeted this way.
    Base.USE_BLAS64 || throw(
        ArgumentError(
            "host_blas = true needs an ILP64 Julia build (`Base.USE_BLAS64` is " *
                "false); the takeover and the placeholder are ILP64-only."
        )
    )
    return nothing
end

"""
    write_host_blas_entry(entry, path) -> String

Write the `juliac` entry file for a `host_blas` build to `path` and return
that path. The file `include`s the shipped takeover module and then the
wrapped `entry` unchanged, so both end up in one library.

The wrapped entry is included rather than copied so that `@__DIR__` and
relative `include`s inside it keep resolving against its own directory.
"""
function write_host_blas_entry(entry::AbstractString, path::AbstractString)
    open(path, "w") do io
        println(io, "# Generated by JuliaLibWrapping for `host_blas = true`. Do not edit.")
        println(io, "#")
        println(io, "# Compiles the host-BLAS takeover into the same `juliac` library as")
        println(io, "# the wrapped entry. Both must share one libjulia: two bundled libraries")
        println(io, "# would each carry their own libblastrampoline, and retargeting one")
        println(io, "# would leave the other on the bundled BLAS.")
        println(io, "include(", repr(abspath(_HOST_BLAS_TAKEOVER_PATH)), ")")
        println(io, "include(", repr(abspath(entry)), ")")
    end
    return path
end

# A C compiler for the placeholder stub. `CC` wins when set, matching the
# usual build convention; otherwise fall back to the common names.
function _find_c_compiler()
    cc = get(ENV, "CC", "")
    isempty(cc) || return cc
    for name in ("cc", "gcc", "clang")
        found = Sys.which(name)
        found === nothing || return found
    end
    error(
        "host_blas = true needs a C compiler to build the libopenblas " *
            "placeholder; set CC or install gcc/clang"
    )
end

"""
    prune_bundle_for_host_blas(bundle_dir; verbose = false)

Remove the bundled OpenBLAS and its gfortran/gomp runtime from the `juliac`
bundle at `bundle_dir`, and replace the OpenBLAS slot with the non-BLAS
placeholder in `openblas_placeholder.c`.

`juliac` always bundles `OpenBLAS_jll` because it is a sysimage stdlib, and
there is no flag to omit it. The placeholder keeps `OpenBLAS_jll`'s dlopen
and libblastrampoline's ILP64 probe working; the runtime takeover then points
every real BLAS call at the host.

Fails when the bundle has no `libopenblas*` to replace, and after the prune
asserts that no remaining bundle library exports `dgemm`.
"""
function prune_bundle_for_host_blas(bundle_dir::AbstractString; verbose::Bool = false)
    julia_dir = joinpath(bundle_dir, "lib", "julia")
    isdir(julia_dir) ||
        error("not a juliac bundle (no lib/julia directory): $bundle_dir")

    names = readdir(julia_dir)
    openblas_names = filter(name -> startswith(name, "libopenblas"), names)
    isempty(openblas_names) && error(
        "host_blas = true expected the bundle at $bundle_dir to contain an " *
            "OpenBLAS library to replace, but lib/julia holds none. The bundle " *
            "was already pruned, or juliac changed how it bundles OpenBLAS_jll."
    )

    drop = ("libopenblas", "libgfortran", "libgomp")
    removed = String[]
    for name in names
        any(prefix -> startswith(name, prefix), drop) || continue
        rm(joinpath(julia_dir, name); force = true)
        push!(removed, name)
    end

    # OpenBLAS_jll dlopens the unversioned name, while the bundle also holds a
    # versioned file and a `.so.0` alias, so the placeholder has to fill every
    # name that was removed rather than just one of them.
    cc = _find_c_compiler()
    stub = joinpath(julia_dir, "jlw_openblas_placeholder.tmp.so")
    run(`$cc -O2 -shared -fPIC -o $stub $(_HOST_BLAS_PLACEHOLDER_C)`)
    for name in openblas_names
        cp(stub, joinpath(julia_dir, name); force = true)
    end
    rm(stub; force = true)

    assert_bundle_has_no_dgemm(bundle_dir; verbose)
    verbose && @info "JuliaLibWrapping: replaced the bundled BLAS with a placeholder" bundle = bundle_dir removed = removed placeholder = openblas_names
    return nothing
end

"""
    assert_bundle_has_no_dgemm(bundle_dir; verbose = false)

Error if any shared library under `bundle_dir` other than
libblastrampoline — a dispatcher, not an implementation — exports `dgemm`.
Used by [`prune_bundle_for_host_blas`](@ref) to prove that the host-BLAS
build ships no second BLAS.
"""
function assert_bundle_has_no_dgemm(bundle_dir::AbstractString; verbose::Bool = false)
    nm = Sys.which("nm")
    if nm === nothing
        verbose && @warn "JuliaLibWrapping: `nm` not found; skipping the no-BLAS check of the bundle"
        return nothing
    end
    for (root, _, files) in walkdir(bundle_dir), f in files
        (endswith(f, ".so") || occursin(r"\.so\.", f)) || continue
        startswith(f, "libblastrampoline") && continue
        path = joinpath(root, f)
        defined = try
            read(`$nm -D --defined-only $path`, String)
        catch
            continue
        end
        occursin("dgemm", defined) &&
            error("host_blas = true left a second BLAS in the bundle: $path exports dgemm")
    end
    return nothing
end

"""
    _write_hostblas_module(f, dest)

Emit the `_hostblas.py` import-time hook for a `host_blas` package. It is
imported from `__init__.py`; it finds a BLAS the host process has already
loaded, calls `hostblas_takeover`, and raises a readable Python exception
when no compatible host BLAS is available. It never calls `exit()`.
"""
function _write_hostblas_module(f::IO, dest::PythonTarget)
    env_var = uppercase(dest.package_name) * "_HOST_BLAS"
    println(f, "\"\"\"Retarget Julia's BLAS at a BLAS the host process has already loaded.")
    println(f)
    println(f, "Imported for its side effect from this package's ``__init__.py``, so that")
    println(f)
    println(f, "    import numpy as np")
    println(f, "    import ", dest.package_name)
    println(f)
    println(f, "leaves Julia's ``LinearAlgebra`` running in the same BLAS -- and the same")
    println(f, "thread pool -- as NumPy. The bundle ships no usable BLAS of its own.")
    println(f)
    println(f, "Generated by JuliaLibWrapping for ``host_blas = true``. Do not edit by hand.")
    println(f, "\"\"\"")
    println(f)
    println(f, "from __future__ import annotations")
    println(f)
    println(f, "import ctypes")
    println(f, "import os")
    println(f)
    println(f, "from . import _lowlevel")
    println(f)
    println(f, "_lib = _lowlevel._lib")
    println(f, "for _name in (\"hostblas_takeover\", \"hostblas_is_ready\", \"hostblas_last_error\"):")
    println(f, "    if not hasattr(_lib, _name):")
    println(f, "        raise RuntimeError(")
    println(f, "            f\"the wrapped library does not export {_name}; rebuild it with \"")
    println(f, "            \"`host_blas = true`\"")
    println(f, "        )")
    println(f)
    println(f, "# The generated bindings describe the path as Ptr{UInt8}; the takeover wants")
    println(f, "# a NUL-terminated string, so bind it as char* here.")
    println(f, "_lib.hostblas_takeover.argtypes = [ctypes.c_char_p]")
    println(f, "_lib.hostblas_takeover.restype = ctypes.c_int32")
    println(f, "_lib.hostblas_last_error.argtypes = [ctypes.c_char_p, ctypes.c_int32]")
    println(f, "_lib.hostblas_last_error.restype = ctypes.c_int32")
    println(f)
    println(f, "# Overrides discovery with one explicit ILP64 BLAS path.")
    println(f, "_HOST_BLAS_ENV_VAR = ", repr(env_var))
    println(f)
    println(f, "# Basenames (substring match) of shared libraries that implement BLAS, in")
    println(f, "# preference order. OpenBLAS comes first: it is what Julia and PyPI NumPy")
    println(f, "# ship, and its ILP64 symbols are namespaced (`scipy_dgemm_64_`), which")
    println(f, "# the takeover knows how to map.")
    println(f, "_BLAS_NAME_HINTS = (")
    println(f, "    \"scipy_openblas\",")
    println(f, "    \"openblas\",")
    println(f, "    \"libblis\",")
    println(f, "    \"libflexiblas\",")
    println(f, "    \"mkl_rt\",")
    println(f, "    \"libatlas\",")
    println(f, ")")
    println(f)
    println(f)
    println(f, "def _loaded_library_paths():")
    println(f, "    \"\"\"Absolute paths of the shared libraries mapped into this process.\"\"\"")
    println(f, "    paths = []")
    println(f, "    seen = set()")
    println(f, "    with open(\"/proc/self/maps\", encoding=\"utf-8\", errors=\"replace\") as fh:")
    println(f, "        for line in fh:")
    println(f, "            fields = line.split(None, 5)")
    println(f, "            if len(fields) < 6:")
    println(f, "                continue")
    println(f, "            path = fields[5].strip()")
    println(f, "            if not path.startswith(\"/\"):")
    println(f, "                continue")
    println(f, "            if path.endswith(\" (deleted)\"):")
    println(f, "                path = path[: -len(\" (deleted)\")]")
    println(f, "            real = os.path.realpath(path)")
    println(f, "            if real in seen:")
    println(f, "                continue")
    println(f, "            seen.add(real)")
    println(f, "            paths.append(real)")
    println(f, "    return paths")
    println(f)
    println(f)
    println(f, "def _candidate_blas_paths():")
    println(f, "    override = os.environ.get(_HOST_BLAS_ENV_VAR)")
    println(f, "    if override:")
    println(f, "        return [override]")
    println(f, "    ranked = []")
    println(f, "    for path in _loaded_library_paths():")
    println(f, "        name = os.path.basename(path)")
    println(f, "        for rank, hint in enumerate(_BLAS_NAME_HINTS):")
    println(f, "            if hint in name:")
    println(f, "                ranked.append((rank, path))")
    println(f, "                break")
    println(f, "    ranked.sort()")
    println(f, "    return [path for _, path in ranked]")
    println(f)
    println(f)
    println(f, "def _last_error():")
    println(f, "    buf = ctypes.create_string_buffer(512)")
    println(f, "    _lib.hostblas_last_error(buf, ctypes.c_int32(len(buf)))")
    println(f, "    return buf.value.decode(\"utf-8\", \"replace\")")
    println(f)
    println(f)
    println(f, "def takeover():")
    println(f, "    \"\"\"Point Julia's libblastrampoline at the host BLAS. Idempotent.\"\"\"")
    println(f, "    if _lib.hostblas_is_ready():")
    println(f, "        return")
    println(f, "    candidates = _candidate_blas_paths()")
    println(f, "    if not candidates:")
    println(f, "        raise RuntimeError(")
    println(f, "            \"no loaded BLAS library found; import the package that provides \"")
    println(f, "            \"the host BLAS (for example numpy) before importing this package, \"")
    println(f, "            \"or set \" + _HOST_BLAS_ENV_VAR + \" to the path of an ILP64 BLAS\"")
    println(f, "        )")
    println(f, "    failures = []")
    println(f, "    for path in candidates:")
    println(f, "        if _lib.hostblas_takeover(os.fsencode(path)) == 0:")
    println(f, "            return")
    println(f, "        failures.append(f\"{path}: {_last_error()}\")")
    println(f, "    raise RuntimeError(")
    println(f, "        \"host BLAS takeover failed for every candidate:\\n  \"")
    println(f, "        + \"\\n  \".join(failures)")
    println(f, "    )")
    println(f)
    println(f)
    println(f, "takeover()")
    return nothing
end
