# Auto-generated by JuliaLibWrapping. Do not edit by hand.
#
# Low-level bindings for the libscalars shared library.
# R/facade.R holds the public API and is created only once; this file is
# rewritten on every build.

# Symbol pointers, resolved once by `.onLoad`.
.jlr_syms <- new.env(parent = emptyenv())

# Compare rdyncall's computed layout against the one the library was
# compiled with. A divergence would otherwise misread every field silently,
# so a mismatch stops the package from loading.
.jlr_check_layout <- function(name, size, alignment, offsets) {
  info <- get(name, envir = parent.frame())
  actual <- as.integer(info$fields$offset)
  names(actual) <- as.character(info$fields$name)
  # `as.integer` drops a vector's names, so restore them before comparing.
  expected <- as.integer(offsets)
  names(expected) <- names(offsets)
  if (info$size != size || info$align != alignment || !identical(actual, expected)) {
    stop(
      sprintf(
        paste0(
          "%s: rdyncall computed size %d, alignment %d and offsets [%s], but ",
          "the library was compiled with size %d, alignment %d and offsets ",
          "[%s]; the generated bindings do not match this platform's ABI"
        ),
        name, info$size, info$align, paste(actual, collapse = ", "),
        size, alignment, paste(expected, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  invisible(NULL)
}

# A `JLWStatus` message is a NUL-terminated byte buffer. The layout check
# above guarantees the field is where the library put it.
.jlr_status_message <- function(status) {
  bytes <- as.raw(status$message)
  nul <- which(bytes == as.raw(0L))
  if (length(nul) > 0L) {
    bytes <- bytes[seq_len(nul[[1L]] - 1L)]
  }
  rawToChar(bytes)
}

# The R condition class for a `JLWStatus` code. An unknown code is a plain
# `jlw_error`.
.jlr_status_class <- function(code) {
  switch(
    as.character(code),
    "1" = "jlw_error",
    "2" = "jlw_argument",
    "3" = "jlw_dimension",
    "4" = "jlw_inexact",
    "5" = "jlw_bounds",
    "jlw_error"
  )
}

.jlr_abort <- function(code, msg) {
  stop(structure(
    class = c(.jlr_status_class(code), "jlw_error", "error", "condition"),
    list(message = msg, call = NULL, code = code)
  ))
}

# Raise on a failed status; a zero code is the only success.
.jlr_check_status <- function(status) {
  if (status$code != 0L) {
    .jlr_abort(status$code, .jlr_status_message(status))
  }
  invisible(NULL)
}

# `as.externalptr` needs a non-empty vector; the carriers' builders use this.
.jlr_extptr <- function(x) {
  as.externalptr(if (length(x) == 0L) as.raw(0L) else x)
}

# Foreign C aggregates, in dependency order.
cstruct("JLWStatus{iC[256]}code message;")
.jlr_check_layout("JLWStatus", size = 260L, alignment = 4L,
                   offsets = c(code = 0L, message = 4L))

cstruct("JLWResult_Float64{<JLWStatus>d}status value;")
.jlr_check_layout("JLWResult_Float64", size = 272L, alignment = 8L,
                   offsets = c(status = 0L, value = 264L))

# Low-level entrypoint bindings. Each signature string is generated
# from the ABI; a mismatch would crash the R process rather than raise.
.jlr_plain_add <- function(a, b) {
  dyncall(get("plain_add", envir = .jlr_syms), "ii)i", a, b)
}

.jlr_do_thing <- function(x) {
  .jlr_result <- dyncall(get("do_thing", envir = .jlr_syms), "i)<JLWStatus>", x)
  .jlr_check_status(.jlr_result)
  invisible(NULL)
}

.jlr_scale_value <- function(x) {
  .jlr_result <- dyncall(get("scale_value", envir = .jlr_syms), "d)<JLWResult_Float64>", x)
  .jlr_check_status(.jlr_result$status)
  .jlr_result$value
}

# The library the package loads, and where to find it.
.jlr_library_basename <- "libscalars"
.jlr_library_env_var <- "LIBSCALARS_R_LIBRARY"
.jlr_symbols <- c(
  "plain_add",
  "do_thing",
  "scale_value"
)

.jlr_library_suffixes <- function() {
  if (.Platform$OS.type == "windows") {
    ".dll"
  } else if (identical(Sys.info()[["sysname"]], "Darwin")) {
    c(".dylib", ".so")
  } else {
    c(".so", ".dylib")
  }
}

# An explicit path may omit the platform's shared-library extension, as the
# MATLAB gateway's `<LIBNAME>_MEX_LIBRARY` accepts. Return the first of
# `base`, `base<suffix>` that exists, or `NULL`.
.jlr_library_candidate <- function(base) {
  for (candidate in paste0(base, c("", .jlr_library_suffixes()))) {
    if (file.exists(candidate)) {
      return(candidate)
    }
  }
  NULL
}

# The directories the loader searches, in order. The shared library and its
# juliac runtime stay where they were built, so a bundle's RUNPATH resolves
# `libjulia` from inside the installed package.
.jlr_library_dirs <- function(libname, pkgname) {
  dirs <- character(0)
  pkgdir <- system.file(package = pkgname, lib.loc = libname)
  if (nzchar(pkgdir)) {
    dirs <- c(dirs, pkgdir, dirname(pkgdir))
  }
  dirs
}

.jlr_resolve_library <- function(libname, pkgname) {
  override <- Sys.getenv(.jlr_library_env_var, unset = "")
  if (nzchar(override)) {
    found <- .jlr_library_candidate(override)
    if (!is.null(found)) {
      return(found)
    }
    stop(
      sprintf(
        paste0(
          "could not find the %s shared library at %s, or beside that path ",
          "with a platform suffix; set %s to an explicit path"
        ),
        .jlr_library_basename, override, .jlr_library_env_var
      ),
      call. = FALSE
    )
  }
  tried <- character(0)
  for (directory in .jlr_library_dirs(libname, pkgname)) {
    for (suffix in c("", .jlr_library_suffixes())) {
      candidate <- paste0(file.path(directory, .jlr_library_basename), suffix)
      tried <- c(tried, candidate)
      if (file.exists(candidate)) {
        return(candidate)
      }
    }
  }
  stop(
    sprintf(
      "could not locate the %s shared library; tried %s; set %s to an explicit path",
      .jlr_library_basename, paste(tried, collapse = ", "), .jlr_library_env_var
    ),
    call. = FALSE
  )
}

.onLoad <- function(libname, pkgname) {
  handle <- dynload(.jlr_resolve_library(libname, pkgname))
  if (is.null(handle)) {
    stop(
      sprintf("could not load the %s shared library", .jlr_library_basename),
      call. = FALSE
    )
  }
  assign(".jlr_handle", handle, envir = .jlr_syms)
  for (symbol in .jlr_symbols) {
    pointer <- dynsym(handle, symbol)
    if (is.null(pointer)) {
      stop(
        sprintf("could not resolve the exported symbol %s", symbol),
        call. = FALSE
      )
    }
    assign(symbol, pointer, envir = .jlr_syms)
  }
  loaded <- getOption("jlw.loaded_r_packages", character(0))
  if (length(loaded) > 0L && !(pkgname %in% loaded)) {
    warning(
      sprintf(
        paste0(
          "loading %s into a process that already loaded %s; this package was ",
          "built without a private libjulia, so both packages resolve a single ",
          "Julia runtime and the first call into whichever did not initialize ",
          "it aborts the process. Rebuild with `privatize = true`, or compile ",
          "both APIs into a single juliac library."
        ),
        pkgname, paste(loaded, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  options(jlw.loaded_r_packages = unique(c(loaded, pkgname)))
  invisible(NULL)
}
