"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import enum
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "enum"
_LIBRARY_ENV_VAR = "ENUM_PY_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

class JLWError(RuntimeError):
    """Raised when a wrapped function returns a non-zero JLWStatus.code."""
    def __init__(self, code, message):
        super().__init__(f"[{code}] {message}")
        self.code = code
        self.message = message

def _check_layout(cls, size, offsets):
    actual = (ctypes.sizeof(cls), *(getattr(cls, name).offset for name, _ in cls._fields_))
    if actual != (size, *offsets):
        raise RuntimeError(
            f"{cls.__name__}: ctypes computed (size, *offsets) {actual}, but the "
            f"library was compiled with {(size, *offsets)}; the generated "
            "bindings do not match this platform's ABI"
        )

class JLWStatus(ctypes.Structure):
    _fields_ = [
        ("code", ctypes.c_int32),
        ("message", (ctypes.c_uint8 * 256)),
    ]
_check_layout(JLWStatus, 260, (0, 4))

class JLWResult_Float64(ctypes.Structure):
    _fields_ = [
        ("status", JLWStatus),
        ("value", ctypes.c_double),
    ]
_check_layout(JLWResult_Float64, 272, (0, 264))

class JLWResult_Int32(ctypes.Structure):
    _fields_ = [
        ("status", JLWStatus),
        ("value", ctypes.c_int32),
    ]
_check_layout(JLWResult_Int32, 264, (0, 260))

# Enum classes declared via `@api` argument/return types.
PenaltyKind = enum.IntEnum("PenaltyKind", [("abslog1", 0), ("square", 1)])

def _enum_coerce(cls, v):
    """Coerce `v` (a member, a member name, or an int) to a member of `cls`."""
    if isinstance(v, str):
        try:
            return cls[v]
        except KeyError:
            raise ValueError(f"invalid {cls.__name__} name {v!r}; valid names: {', '.join(cls.__members__)}") from None
    return cls(v)

_lib.EnumFixture_scale_by.argtypes = [ctypes.c_double, ctypes.c_int32]
_lib.EnumFixture_scale_by.restype = JLWResult_Float64
def EnumFixture_scale_by(x, penalty):
    """Scale `x`, squaring it when `penalty` is not `abslog1`."""
    _result = _lib.EnumFixture_scale_by(x, penalty)
    if _result.status.code != 0:
        _msg = bytes(_result.status.message).rstrip(b"\x00").decode("utf-8", errors="replace")
        raise JLWError(_result.status.code, _msg)
    return _result

_lib.EnumFixture_pick.argtypes = [ctypes.c_double]
_lib.EnumFixture_pick.restype = JLWResult_Int32
def EnumFixture_pick(x):
    """Classify the sign of `x` as a PenaltyKind."""
    _result = _lib.EnumFixture_pick(x)
    if _result.status.code != 0:
        _msg = bytes(_result.status.message).rstrip(b"\x00").decode("utf-8", errors="replace")
        raise JLWError(_result.status.code, _msg)
    return _result

