# Auto-generated by JuliaLibWrapping. Do not edit by hand.
#
# Low-level bindings for the libcarray3 shared library.
# R/facade.R holds the public API and is created only once; this file is
# rewritten on every build.

# Symbol pointers, resolved once by `.onLoad`.
.jlr_syms <- new.env(parent = emptyenv())

# Compare rdyncall's computed layout against the one the library was
# compiled with. A divergence would otherwise misread every field silently,
# so a mismatch stops the package from loading.
.jlr_check_layout <- function(name, size, alignment, offsets) {
  info <- get(name, envir = parent.frame())
  actual <- as.integer(info$fields$offset)
  names(actual) <- as.character(info$fields$name)
  # `as.integer` drops a vector's names, so restore them before comparing.
  expected <- as.integer(offsets)
  names(expected) <- names(offsets)
  if (info$size != size || info$align != alignment || !identical(actual, expected)) {
    stop(
      sprintf(
        paste0(
          "%s: rdyncall computed size %d, alignment %d and offsets [%s], but ",
          "the library was compiled with size %d, alignment %d and offsets ",
          "[%s]; the generated bindings do not match this platform's ABI"
        ),
        name, info$size, info$align, paste(actual, collapse = ", "),
        size, alignment, paste(expected, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  invisible(NULL)
}

# A `JLWStatus` message is a NUL-terminated byte buffer. The layout check
# above guarantees the field is where the library put it.
.jlr_status_message <- function(status) {
  bytes <- as.raw(status$message)
  nul <- which(bytes == as.raw(0L))
  if (length(nul) > 0L) {
    bytes <- bytes[seq_len(nul[[1L]] - 1L)]
  }
  rawToChar(bytes)
}

# The R condition class for a `JLWStatus` code. An unknown code is a plain
# `jlw_error`.
.jlr_status_class <- function(code) {
  switch(
    as.character(code),
    "1" = "jlw_error",
    "2" = "jlw_argument",
    "3" = "jlw_dimension",
    "4" = "jlw_inexact",
    "5" = "jlw_bounds",
    "jlw_error"
  )
}

.jlr_abort <- function(code, msg) {
  stop(structure(
    class = c(.jlr_status_class(code), "jlw_error", "error", "condition"),
    list(message = msg, call = NULL, code = code)
  ))
}

# Raise on a failed status; a zero code is the only success.
.jlr_check_status <- function(status) {
  if (status$code != 0L) {
    .jlr_abort(status$code, .jlr_status_message(status))
  }
  invisible(NULL)
}

# Foreign C aggregates, in dependency order.
cstruct("CArray_borrowed_Float64_3{l[3]*d}dims data;")
.jlr_check_layout("CArray_borrowed_Float64_3", size = 32L, alignment = 8L,
                   offsets = c(dims = 0L, data = 24L))

.jlr_CArray_borrowed_Float64_3_arg <- function(x) {
  .jlr_n <- length(x)
  if (is.null(dim(x))) {
    stop("expected a 3-D array")
  }
  .jlr_dims <- as.integer(dim(x))
  .jlr_data <- as.externalptr(as.double(x))
  .jlr_carrier <- cdata("CArray_borrowed_Float64_3")
  .jlr_carrier$dims <- .jlr_dims
  .jlr_carrier$data <- .jlr_data
  .jlr_carrier
}

.jlr_CArray_borrowed_Float64_3_ret <- function(s) {
  .jlr_dims <- as.integer(s$dims)
  .jlr_n <- as.integer(prod(.jlr_dims))
  .jlr_out <- numeric(.jlr_n)
  for (.jlr_i in seq_len(.jlr_n)) {
    .jlr_out[.jlr_i] <- unpack(s$data, (.jlr_i - 1L) * 8, "d")
  }
  if (length(.jlr_dims) > 1L) {
    dim(.jlr_out) <- .jlr_dims
  }
  .jlr_out
}

# Low-level entrypoint bindings. Each signature string is generated
# from the ABI; a mismatch would crash the R process rather than raise.
.jlr_sum3d <- function(a) {
  dyncall(get("sum3d", envir = .jlr_syms), "<CArray_borrowed_Float64_3>)d", a)
}

# The library the package loads, and where to find it.
.jlr_library_basename <- "libcarray3"
.jlr_library_env_var <- "LIBCARRAY3_R_LIBRARY"
.jlr_symbols <- c(
  "sum3d"
)

.jlr_library_suffixes <- function() {
  if (.Platform$OS.type == "windows") {
    ".dll"
  } else if (identical(Sys.info()[["sysname"]], "Darwin")) {
    c(".dylib", ".so")
  } else {
    c(".so", ".dylib")
  }
}

# The directories the loader searches, in order. The shared library and its
# juliac runtime stay where they were built, so a bundle's RUNPATH resolves
# `libjulia` from inside the installed package.
.jlr_library_dirs <- function(libname, pkgname) {
  dirs <- character(0)
  pkgdir <- system.file(package = pkgname, lib.loc = libname)
  if (nzchar(pkgdir)) {
    dirs <- c(dirs, pkgdir, dirname(pkgdir))
  }
  dirs
}

.jlr_resolve_library <- function(libname, pkgname) {
  override <- Sys.getenv(.jlr_library_env_var, unset = "")
  if (nzchar(override)) {
    return(override)
  }
  tried <- character(0)
  for (directory in .jlr_library_dirs(libname, pkgname)) {
    for (suffix in .jlr_library_suffixes()) {
      candidate <- file.path(directory, paste0(.jlr_library_basename, suffix))
      tried <- c(tried, candidate)
      if (file.exists(candidate)) {
        return(candidate)
      }
    }
  }
  stop(
    sprintf(
      "could not locate the %s shared library; tried %s; set %s to an explicit path",
      .jlr_library_basename, paste(tried, collapse = ", "), .jlr_library_env_var
    ),
    call. = FALSE
  )
}

.onLoad <- function(libname, pkgname) {
  handle <- dynload(.jlr_resolve_library(libname, pkgname))
  if (is.null(handle)) {
    stop(
      sprintf("could not load the %s shared library", .jlr_library_basename),
      call. = FALSE
    )
  }
  assign(".jlr_handle", handle, envir = .jlr_syms)
  for (symbol in .jlr_symbols) {
    pointer <- dynsym(handle, symbol)
    if (is.null(pointer)) {
      stop(
        sprintf("could not resolve the exported symbol %s", symbol),
        call. = FALSE
      )
    }
    assign(symbol, pointer, envir = .jlr_syms)
  }
  loaded <- getOption("jlw.loaded_r_packages", character(0))
  if (length(loaded) > 0L && !(pkgname %in% loaded)) {
    warning(
      sprintf(
        paste0(
          "loading %s into a process that already loaded %s; this package was ",
          "built without a private libjulia, so both packages resolve a single ",
          "Julia runtime and the first call into whichever did not initialize ",
          "it aborts the process. Rebuild with `privatize = true`, or compile ",
          "both APIs into a single juliac library."
        ),
        pkgname, paste(loaded, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  options(jlw.loaded_r_packages = unique(c(loaded, pkgname)))
  invisible(NULL)
}
