"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib
import numpy as np

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libcarrayowned"
_LIBRARY_ENV_VAR = "CARRAY_OWNED_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

class CString_owned(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        return self.as_bytes().decode("utf-8")

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. For callers who bypass the
        façade's convert-then-free wrapper and talk to `_lowlevel` directly."""
        if getattr(self, "_freed", False):
            return
        _lib.jlw_free(ctypes.cast(self.data, ctypes.c_void_p))
        self._freed = True

class CVector_owned_Float64(ctypes.Structure):
    _fields_ = [
        ("dims", (ctypes.c_int32 * 1)),
        ("data", ctypes.POINTER(ctypes.c_double)),
    ]

    def as_numpy(self):
        """Return a 1-D numpy view of the underlying buffer (no copy)."""
        return np.ctypeslib.as_array(self.data, shape=(self.dims[0],))

    def free(self):
        """Free the Julia-allocated buffer.

        Idempotent: a second call is a no-op. For callers who bypass the
        façade's convert-then-free wrapper and talk to `_lowlevel` directly."""
        if getattr(self, "_freed", False):
            return
        _lib.jlw_free(ctypes.cast(self.data, ctypes.c_void_p))
        self._freed = True

_lib.give_vec.argtypes = []
_lib.give_vec.restype = CVector_owned_Float64
def give_vec():
    return _lib.give_vec()

_lib.jlw_free.argtypes = [ctypes.c_void_p]
_lib.jlw_free.restype = None

_lib.jlw_free_strings.argtypes = [ctypes.POINTER(CString_owned), ctypes.c_int64]
_lib.jlw_free_strings.restype = None

