"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib
import numpy as np

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libsimple"
_LIBRARY_ENV_VAR = "LIBSIMPLE_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

def _check_layout(cls, size, offsets):
    actual = (ctypes.sizeof(cls), *(getattr(cls, name).offset for name, _ in cls._fields_))
    if actual != (size, *offsets):
        raise RuntimeError(
            f"{cls.__name__}: ctypes computed (size, *offsets) {actual}, but the "
            f"library was compiled with {(size, *offsets)}; the generated "
            "bindings do not match this platform's ABI"
        )

# Forward declarations for recursive types
class CTree_Float64(ctypes.Structure):
    pass

class CVector_borrowed_Float32(ctypes.Structure):
    _fields_ = [
        ("dims", (ctypes.c_int64 * 1)),
        ("data", ctypes.POINTER(ctypes.c_float)),
    ]

    @classmethod
    def from_numpy(cls, arr):
        """Return a CArray view of the 1-D numpy array `arr`.

        Raises ValueError on ndim, contiguity, or dtype mismatch (fail-fast: no
        silent reinterpretation). The returned object holds a reference to `arr`,
        so the caller must keep it alive for the duration of any C call that uses
        the buffer."""
        if arr.ndim != 1:
            raise ValueError(f"expected 1-D array, got {arr.ndim}-D")
        if not (arr.flags.c_contiguous or arr.flags.f_contiguous):
            raise ValueError("array must be contiguous")
        expected_dtype = np.dtype("float32")
        if arr.dtype != expected_dtype:
            raise ValueError(f"expected dtype float32, got {arr.dtype}")
        obj = cls(dims=(ctypes.c_int64 * 1)(*arr.shape),
                  data=arr.ctypes.data_as(ctypes.POINTER(ctypes.c_float)))
        obj._buffer = arr
        return obj

    def as_numpy(self):
        """Return a 1-D numpy view of the underlying buffer (no copy)."""
        return np.ctypeslib.as_array(self.data, shape=(self.dims[0],))
_check_layout(CVector_borrowed_Float32, 16, (0, 8))

class CVectorPair_Float32(ctypes.Structure):
    _fields_ = [
        ("from_", CVector_borrowed_Float32),
        ("to", CVector_borrowed_Float32),
    ]
_check_layout(CVectorPair_Float32, 32, (0, 16))

class MyTwoVec(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_int32),
        ("y", ctypes.c_int32),
    ]
_check_layout(MyTwoVec, 8, (0, 4))

class CVector_borrowed_CTree_Float64(ctypes.Structure):
    _fields_ = [
        ("dims", (ctypes.c_int64 * 1)),
        ("data", ctypes.POINTER(CTree_Float64)),
    ]
_check_layout(CVector_borrowed_CTree_Float64, 16, (0, 8))

CTree_Float64._fields_ = [
    ("children", CVector_borrowed_CTree_Float64),
]
_check_layout(CTree_Float64, 16, (0,))

_lib.tree_size.argtypes = [CTree_Float64]
_lib.tree_size.restype = ctypes.c_int64
def tree_size(tree):
    return _lib.tree_size(tree)

_lib.copyto_and_sum.argtypes = [CVectorPair_Float32]
_lib.copyto_and_sum.restype = ctypes.c_float
def copyto_and_sum(fromto):
    return _lib.copyto_and_sum(fromto)

_lib.countsame.argtypes = [ctypes.POINTER(MyTwoVec), ctypes.c_int32]
_lib.countsame.restype = ctypes.c_int32
def countsame(list, n):
    return _lib.countsame(list, n)

