"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libcstrarraynofree"
_LIBRARY_ENV_VAR = "CSTRARRAY_NOFREE_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

class Nothing(ctypes.Structure):
    _fields_ = []

class CStrArray(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("data", ctypes.POINTER(ctypes.POINTER(ctypes.c_uint8))),
    ]

    @classmethod
    def from_list(cls, items):
        if not isinstance(items, (list, tuple)):
            raise TypeError("expected a list of str")
        bufs = [s.encode("utf-8") + b"\x00" for s in items]
        arr = (ctypes.POINTER(ctypes.c_uint8) * len(bufs))(
            *[ctypes.cast(ctypes.create_string_buffer(b, len(b)), ctypes.POINTER(ctypes.c_uint8)) for b in bufs])
        obj = cls(length=len(bufs), data=ctypes.cast(arr, ctypes.POINTER(ctypes.POINTER(ctypes.c_uint8))))
        obj._buffer = (bufs, arr)   # keepalive — the from_numpy pattern
        return obj

    def as_list(self):
        out = []
        for i in range(self.length):
            p = ctypes.cast(self.data[i], ctypes.c_char_p)
            out.append(p.value.decode("utf-8"))
        return out

_lib.take_strs.argtypes = [CStrArray]
_lib.take_strs.restype = ctypes.c_int64
def take_strs(a):
    return _lib.take_strs(a)

_lib.give_strs.argtypes = []
_lib.give_strs.restype = CStrArray
def give_strs():
    return _lib.give_strs()

