# Auto-generated by JuliaLibWrapping. Do not edit by hand.
#
# Low-level bindings for the libcdict shared library.
# R/facade.R holds the public API and is created only once; this file is
# rewritten on every build.

# Symbol pointers, resolved once by `.onLoad`.
.jlr_syms <- new.env(parent = emptyenv())

# Compare rdyncall's computed layout against the one the library was
# compiled with. A divergence would otherwise misread every field silently,
# so a mismatch stops the package from loading.
.jlr_check_layout <- function(name, size, alignment, offsets) {
  info <- get(name, envir = parent.frame())
  actual <- as.integer(info$fields$offset)
  names(actual) <- as.character(info$fields$name)
  # `as.integer` drops a vector's names, so restore them before comparing.
  expected <- as.integer(offsets)
  names(expected) <- names(offsets)
  if (info$size != size || info$align != alignment || !identical(actual, expected)) {
    stop(
      sprintf(
        paste0(
          "%s: rdyncall computed size %d, alignment %d and offsets [%s], but ",
          "the library was compiled with size %d, alignment %d and offsets ",
          "[%s]; the generated bindings do not match this platform's ABI"
        ),
        name, info$size, info$align, paste(actual, collapse = ", "),
        size, alignment, paste(expected, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  invisible(NULL)
}

# A `JLWStatus` message is a NUL-terminated byte buffer. The layout check
# above guarantees the field is where the library put it.
.jlr_status_message <- function(status) {
  bytes <- as.raw(status$message)
  nul <- which(bytes == as.raw(0L))
  if (length(nul) > 0L) {
    bytes <- bytes[seq_len(nul[[1L]] - 1L)]
  }
  rawToChar(bytes)
}

# The R condition class for a `JLWStatus` code. An unknown code is a plain
# `jlw_error`.
.jlr_status_class <- function(code) {
  switch(
    as.character(code),
    "1" = "jlw_error",
    "2" = "jlw_argument",
    "3" = "jlw_dimension",
    "4" = "jlw_inexact",
    "5" = "jlw_bounds",
    "jlw_error"
  )
}

.jlr_abort <- function(code, msg) {
  stop(structure(
    class = c(.jlr_status_class(code), "jlw_error", "error", "condition"),
    list(message = msg, call = NULL, code = code)
  ))
}

# Raise on a failed status; a zero code is the only success.
.jlr_check_status <- function(status) {
  if (status$code != 0L) {
    .jlr_abort(status$code, .jlr_status_message(status))
  }
  invisible(NULL)
}

# Foreign C aggregates, in dependency order.
cstruct("CString_borrowed{l*C}length data;")
.jlr_check_layout("CString_borrowed", size = 16L, alignment = 8L,
                   offsets = c(length = 0L, data = 8L))

cstruct("CString_owned{l*C}length data;")
.jlr_check_layout("CString_owned", size = 16L, alignment = 8L,
                   offsets = c(length = 0L, data = 8L))

cstruct("CDict_borrowed_Float64{l*<CString_borrowed>*d}length keys values;")
.jlr_check_layout("CDict_borrowed_Float64", size = 24L, alignment = 8L,
                   offsets = c(length = 0L, keys = 8L, values = 16L))

cstruct("CDict_owned_Float64{l*<CString_owned>*d}length keys values;")
.jlr_check_layout("CDict_owned_Float64", size = 24L, alignment = 8L,
                   offsets = c(length = 0L, keys = 8L, values = 16L))

.jlr_CString_borrowed_arg <- function(x) {
  .jlr_bytes <- charToRaw(enc2utf8(as.character(x)))
  .jlr_carrier <- cdata("CString_borrowed")
  .jlr_carrier$length <- length(.jlr_bytes)
  .jlr_carrier$data <- as.externalptr(.jlr_bytes)
  .jlr_carrier
}

.jlr_CString_borrowed_ret <- function(s) {
  .jlr_bytes <- raw(as.integer(s$length))
  for (.jlr_i in seq_len(length(.jlr_bytes))) {
    .jlr_bytes[.jlr_i] <- as.raw(unpack(s$data, .jlr_i - 1L, "C"))
  }
  .jlr_nul <- which(.jlr_bytes == as.raw(0L))
  if (length(.jlr_nul) > 0L) {
    .jlr_bytes <- .jlr_bytes[seq_len(.jlr_nul[[1L]] - 1L)]
  }
  rawToChar(.jlr_bytes)
}

.jlr_CString_owned_ret <- function(s) {
  on.exit(.jlr_jlw_free(s$data), add = TRUE)
  .jlr_bytes <- raw(as.integer(s$length))
  for (.jlr_i in seq_len(length(.jlr_bytes))) {
    .jlr_bytes[.jlr_i] <- as.raw(unpack(s$data, .jlr_i - 1L, "C"))
  }
  .jlr_nul <- which(.jlr_bytes == as.raw(0L))
  if (length(.jlr_nul) > 0L) {
    .jlr_bytes <- .jlr_bytes[seq_len(.jlr_nul[[1L]] - 1L)]
  }
  rawToChar(.jlr_bytes)
}

.jlr_CDict_borrowed_Float64_arg <- function(x) {
  .jlr_keys <- names(x)
  if (is.null(.jlr_keys)) {
    stop("a CDict argument needs a named vector or list")
  }
  .jlr_n <- length(.jlr_keys)
  .jlr_bufs <- lapply(.jlr_keys, function(key) charToRaw(enc2utf8(key)))
  .jlr_karr <- raw(.jlr_n * 16)
  for (.jlr_i in seq_len(.jlr_n)) {
    .jlr_off <- (.jlr_i - 1L) * 16L
    pack(.jlr_karr, .jlr_off + 0L, "l", length(.jlr_bufs[[.jlr_i]]))
    pack(.jlr_karr, .jlr_off + 8L, "p", as.externalptr(.jlr_bufs[[.jlr_i]]))
  }
  .jlr_varr <- raw(.jlr_n * 8)
  for (.jlr_i in seq_len(.jlr_n)) {
    pack(.jlr_varr, (.jlr_i - 1L) * 8L, "d", x[[.jlr_i]])
  }
  .jlr_carrier <- cdata("CDict_borrowed_Float64")
  .jlr_carrier$length <- .jlr_n
  .jlr_carrier$keys <- as.externalptr(.jlr_karr)
  .jlr_carrier$values <- as.externalptr(.jlr_varr)
  .jlr_carrier
}

.jlr_CDict_borrowed_Float64_ret <- function(s) {
  .jlr_n <- as.integer(s$length)
  .jlr_out <- numeric(.jlr_n)
  .jlr_names <- character(.jlr_n)
  for (.jlr_i in seq_len(.jlr_n)) {
    .jlr_off <- (.jlr_i - 1L) * 16L
    .jlr_len <- as.integer(unpack(s$keys, .jlr_off + 0L, "l"))
    .jlr_ptr <- unpack(s$keys, .jlr_off + 8L, "p")
    .jlr_bytes <- raw(.jlr_len)
    for (.jlr_j in seq_len(.jlr_len)) {
      .jlr_bytes[.jlr_j] <- as.raw(unpack(.jlr_ptr, .jlr_j - 1L, "C"))
    }
    .jlr_nul <- which(.jlr_bytes == as.raw(0L))
    if (length(.jlr_nul) > 0L) {
      .jlr_bytes <- .jlr_bytes[seq_len(.jlr_nul[[1L]] - 1L)]
    }
    .jlr_names[.jlr_i] <- rawToChar(.jlr_bytes)
    .jlr_out[.jlr_i] <- unpack(s$values, (.jlr_i - 1L) * 8L, "d")
  }
  names(.jlr_out) <- .jlr_names
  .jlr_out
}

.jlr_CDict_owned_Float64_ret <- function(s) {
  on.exit({
    .jlr_jlw_free_strings(s$keys, s$length)
    .jlr_jlw_free(s$values)
  }, add = TRUE)
  .jlr_n <- as.integer(s$length)
  .jlr_out <- numeric(.jlr_n)
  .jlr_names <- character(.jlr_n)
  for (.jlr_i in seq_len(.jlr_n)) {
    .jlr_off <- (.jlr_i - 1L) * 16L
    .jlr_len <- as.integer(unpack(s$keys, .jlr_off + 0L, "l"))
    .jlr_ptr <- unpack(s$keys, .jlr_off + 8L, "p")
    .jlr_bytes <- raw(.jlr_len)
    for (.jlr_j in seq_len(.jlr_len)) {
      .jlr_bytes[.jlr_j] <- as.raw(unpack(.jlr_ptr, .jlr_j - 1L, "C"))
    }
    .jlr_nul <- which(.jlr_bytes == as.raw(0L))
    if (length(.jlr_nul) > 0L) {
      .jlr_bytes <- .jlr_bytes[seq_len(.jlr_nul[[1L]] - 1L)]
    }
    .jlr_names[.jlr_i] <- rawToChar(.jlr_bytes)
    .jlr_out[.jlr_i] <- unpack(s$values, (.jlr_i - 1L) * 8L, "d")
  }
  names(.jlr_out) <- .jlr_names
  .jlr_out
}

# Low-level entrypoint bindings. Each signature string is generated
# from the ABI; a mismatch would crash the R process rather than raise.
.jlr_take_dict <- function(d) {
  dyncall(get("take_dict", envir = .jlr_syms), "<CDict_borrowed_Float64>)l", d)
}

.jlr_give_dict <- function() {
  dyncall(get("give_dict", envir = .jlr_syms), ")<CDict_owned_Float64>")
}

.jlr_jlw_free <- function(p) {
  dyncall(get("jlw_free", envir = .jlr_syms), "p)v", p)
  invisible(NULL)
}

.jlr_jlw_free_strings <- function(p, n) {
  dyncall(get("jlw_free_strings", envir = .jlr_syms), "pl)v", p, n)
  invisible(NULL)
}

# The library the package loads, and where to find it.
.jlr_library_basename <- "libcdict"
.jlr_library_env_var <- "LIBCDICT_R_LIBRARY"
.jlr_symbols <- c(
  "take_dict",
  "give_dict",
  "jlw_free",
  "jlw_free_strings"
)

.jlr_library_suffixes <- function() {
  if (.Platform$OS.type == "windows") {
    ".dll"
  } else if (identical(Sys.info()[["sysname"]], "Darwin")) {
    c(".dylib", ".so")
  } else {
    c(".so", ".dylib")
  }
}

# The directories the loader searches, in order. The shared library and its
# juliac runtime stay where they were built, so a bundle's RUNPATH resolves
# `libjulia` from inside the installed package.
.jlr_library_dirs <- function(libname, pkgname) {
  dirs <- character(0)
  pkgdir <- system.file(package = pkgname, lib.loc = libname)
  if (nzchar(pkgdir)) {
    dirs <- c(dirs, pkgdir, dirname(pkgdir))
  }
  dirs
}

.jlr_resolve_library <- function(libname, pkgname) {
  override <- Sys.getenv(.jlr_library_env_var, unset = "")
  if (nzchar(override)) {
    return(override)
  }
  tried <- character(0)
  for (directory in .jlr_library_dirs(libname, pkgname)) {
    for (suffix in .jlr_library_suffixes()) {
      candidate <- file.path(directory, paste0(.jlr_library_basename, suffix))
      tried <- c(tried, candidate)
      if (file.exists(candidate)) {
        return(candidate)
      }
    }
  }
  stop(
    sprintf(
      "could not locate the %s shared library; tried %s; set %s to an explicit path",
      .jlr_library_basename, paste(tried, collapse = ", "), .jlr_library_env_var
    ),
    call. = FALSE
  )
}

.onLoad <- function(libname, pkgname) {
  handle <- dynload(.jlr_resolve_library(libname, pkgname))
  if (is.null(handle)) {
    stop(
      sprintf("could not load the %s shared library", .jlr_library_basename),
      call. = FALSE
    )
  }
  assign(".jlr_handle", handle, envir = .jlr_syms)
  for (symbol in .jlr_symbols) {
    pointer <- dynsym(handle, symbol)
    if (is.null(pointer)) {
      stop(
        sprintf("could not resolve the exported symbol %s", symbol),
        call. = FALSE
      )
    }
    assign(symbol, pointer, envir = .jlr_syms)
  }
  loaded <- getOption("jlw.loaded_r_packages", character(0))
  if (length(loaded) > 0L && !(pkgname %in% loaded)) {
    warning(
      sprintf(
        paste0(
          "loading %s into a process that already loaded %s; this package was ",
          "built without a private libjulia, so both packages resolve a single ",
          "Julia runtime and the first call into whichever did not initialize ",
          "it aborts the process. Rebuild with `privatize = true`, or compile ",
          "both APIs into a single juliac library."
        ),
        pkgname, paste(loaded, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  options(jlw.loaded_r_packages = unique(c(loaded, pkgname)))
  invisible(NULL)
}
