/* Auto-generated by JuliaLibWrapping. Do not edit by hand. */
#ifndef _GNU_SOURCE
#define _GNU_SOURCE  /* dladdr */
#endif
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include <fcntl.h>
#include "mex.h"
#include "libctuple_mex_types.h"

/* Where the shared library is, in the order the loader tries:
   the environment variable, then this MEX file's own directory,
   then the path `build_mex.m` compiled in. The relative one is
   what lets a built package be moved or downloaded, since the
   layout it names is the one this target emits. A bare name
   would resolve against MATLAB's working directory instead. */
#ifndef JLW_LIBRARY_PATH
#define JLW_LIBRARY_PATH "libctuple"
#endif
#define JLW_LIBRARY_RELATIVE "../../libctuple"
#define JLW_LIBRARY_ENV "LIBCTUPLE_MEX_LIBRARY"

static void *jlw_library = NULL;

/* Julia's runtime marks inherited pipes non-blocking and leaves
   them that way, which MATLAB's own reads then see as errors.
   It bites when MATLAB runs under -batch in a pipeline. */
typedef struct { int flags[3]; } jlw_stdio_flags;

static jlw_stdio_flags jlw_save_stdio(void)
{
    jlw_stdio_flags saved;
    for (int fd = 0; fd < 3; fd++) {
        saved.flags[fd] = fcntl(fd, F_GETFL);
    }
    return saved;
}

static void jlw_restore_stdio(jlw_stdio_flags saved)
{
    for (int fd = 0; fd < 3; fd++) {
        if (saved.flags[fd] != -1) {
            fcntl(fd, F_SETFL, saved.flags[fd]);
        }
    }
}

/* The directory holding this MEX file, so the library can be found
   beside it wherever the package was put. */
static void jlw_own_directory(char *out, size_t size)
{
    Dl_info info;
    out[0] = '\0';
    if (dladdr((void *)jlw_own_directory, &info) == 0 ||
        info.dli_fname == NULL) {
        return;
    }
    snprintf(out, size, "%s", info.dli_fname);
    char *slash = strrchr(out, '/');
    if (slash == NULL) {
        out[0] = '\0';
        return;
    }
    *slash = '\0';
}

/* Local: every entry point is reached through this handle, and the
   runtime finds its own image from the address of the caller, so
   nothing here needs the global scope. Loading it globally would
   publish this library's unversioned names -- the entry points,
   `jlw_free`, the image symbols -- where a second wrapped library
   would find them. */
static void *jlw_open(const char *base)
{
    char path[4096];
#ifdef __APPLE__
    snprintf(path, sizeof path, "%s.dylib", base);
#else
    snprintf(path, sizeof path, "%s.so", base);
#endif
    return dlopen(path, RTLD_LAZY | RTLD_NODELETE);
}

/* Opened once and never closed. Nothing releases this reference, so
   `clear mex` leaves the library mapped and the next load finds it
   rather than running `jl_init` a second time. */
static void *jlw_symbol(const char *name)
{
    if (jlw_library == NULL) {
        jlw_stdio_flags saved = jlw_save_stdio();
        const char *override = getenv(JLW_LIBRARY_ENV);
        char own[4096];
        char beside[4096];
        beside[0] = '\0';
        jlw_own_directory(own, sizeof own);
        if (own[0] != '\0') {
            snprintf(beside, sizeof beside, "%s/" JLW_LIBRARY_RELATIVE, own);
        }
        if (override != NULL) {
            jlw_library = jlw_open(override);
        }
        if (jlw_library == NULL && beside[0] != '\0') {
            jlw_library = jlw_open(beside);
        }
        if (jlw_library == NULL) {
            jlw_library = jlw_open(JLW_LIBRARY_PATH);
        }
        if (jlw_library == NULL) {
            const char *message = dlerror();
            mexErrMsgIdAndTxt("jlw:library",
                "could not load %s (%s); set " JLW_LIBRARY_ENV
                " to its path without the extension",
                JLW_LIBRARY_PATH, message ? message : "");
        }
        jlw_restore_stdio(saved);
    }
    void *address = dlsym(jlw_library, name);
    if (address == NULL) {
        mexErrMsgIdAndTxt("jlw:library", "missing entry point %s", name);
    }
    return address;
}

/* Raises, so every caller must release what it holds before calling:
   `mexErrMsgIdAndTxt` leaves by `longjmp`, which runs no cleanup. */
static void jlw_check(JLWStatus status)
{
    if (status.code == 0) {
        return;
    }
    char message[256 + 1];
    memcpy(message, status.message, 256);
    message[256] = '\0';
    const char *identifier;
    switch (status.code) {
        case 1: identifier = "jlw:error"; break;
        case 2: identifier = "jlw:argument"; break;
        case 3: identifier = "jlw:dimension"; break;
        case 4: identifier = "jlw:inexact"; break;
        case 5: identifier = "jlw:bounds"; break;
        default: identifier = "jlw:error"; break;
    }
    mexErrMsgIdAndTxt(identifier, "%s", message);
}

static int jlw_valid_field_name(const uint8_t *data, int32_t n)
{
    if (n <= 0 || n >= mxMAXNAM) {
        return 0;
    }
    for (int32_t j = 0; j < n; j++) {
        uint8_t c = data[j];
        int alpha = (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z');
        int rest = (c >= '0' && c <= '9') || c == '_';
        /* A field name starts with a letter. */
        if (!(j == 0 ? alpha : (alpha || rest))) {
            return 0;
        }
    }
    return 1;
}

static void jlw_release(void *pointer)
{
    static void (*entry)(void *) = NULL;
    if (entry == NULL) {
        entry = (void (*)(void *))jlw_symbol("jlw_free");
    }
    entry(pointer);
}

static void jlw_release_strings(void *items, int64_t count)
{
    static void (*entry)(void *, int64_t) = NULL;
    if (entry == NULL) {
        entry = (void (*)(void *, int64_t))jlw_symbol("jlw_free_strings");
    }
    entry(items, count);
}

static mxArray *jlw_out_CString_owned(CString_owned carrier)
{
    /* `mxCreateString` takes a C string, so an embedded NUL
       truncates; Julia permits them. */
    char *text = (char *)mxMalloc((size_t)carrier.length + 1);
    memcpy(text, carrier.data, (size_t)carrier.length);
    text[carrier.length] = '\0';
    jlw_release(carrier.data);
    mxArray *out = mxCreateString(text);
    mxFree(text);
    return out;
}

static mxArray *jlw_out_CStrArray_owned(CStrArray_owned carrier)
{
    mxArray *out = mxCreateCellMatrix((mwSize)carrier.length, 1);
    for (int64_t i = 0; i < carrier.length; i++) {
        char *text = (char *)mxMalloc((size_t)carrier.data[i].length + 1);
        memcpy(text, carrier.data[i].data, (size_t)carrier.data[i].length);
        text[carrier.data[i].length] = '\0';
        mxSetCell(out, (mwSize)i, mxCreateString(text));
        mxFree(text);
    }
    jlw_release_strings(carrier.data, carrier.length);
    return out;
}

static mxArray *jlw_out_CDict_owned_Float64(CDict_owned_Float64 carrier)
{
    /* Keys are checked before anything is created, so a bad
       one is reported while nothing is held. */
    for (int64_t i = 0; i < carrier.length; i++) {
        if (!jlw_valid_field_name(carrier.keys[i].data, carrier.keys[i].length)) {
            jlw_release_strings(carrier.keys, carrier.length);
            jlw_release(carrier.values);
            mexErrMsgIdAndTxt("jlw:argument",
                "a dictionary key is not a legal MATLAB field name");
        }
    }
    const char **names =
        (const char **)mxMalloc((size_t)(carrier.length ? carrier.length : 1) * sizeof(char *));
    for (int64_t i = 0; i < carrier.length; i++) {
        char *key = (char *)mxMalloc((size_t)carrier.keys[i].length + 1);
        memcpy(key, carrier.keys[i].data, (size_t)carrier.keys[i].length);
        key[carrier.keys[i].length] = '\0';
        names[i] = key;
    }
    mxArray *out = mxCreateStructMatrix(1, 1, (int)carrier.length, names);
    for (int64_t i = 0; i < carrier.length; i++) {
        mxArray *field = mxCreateNumericMatrix(1, 1, mxDOUBLE_CLASS, mxREAL);
        *mxGetDoubles(field) = (double)carrier.values[i];
        mxSetFieldByNumber(out, 0, (int)i, field);
    }
    jlw_release_strings(carrier.keys, carrier.length);
    jlw_release(carrier.values);
    return out;
}

static mxArray *jlw_out_COpt_Float64(COpt_Float64 carrier)
{
    if (carrier.has_value == 0) {
        return mxCreateNumericMatrix(0, 0, mxDOUBLE_CLASS, mxREAL);
    }
    mxArray *out = mxCreateNumericMatrix(1, 1, mxDOUBLE_CLASS, mxREAL);
    *mxGetDoubles(out) = carrier.value;
    return out;
}

static mxArray *jlw_out_CVector_owned_Float64(CVector_owned_Float64 carrier)
{
    mwSize shape[2] = {1, 1};
    shape[0] = (mwSize)carrier.dims[0];
    mxArray *out = mxCreateNumericArray(2, shape, mxDOUBLE_CLASS, mxREAL);
    memcpy(mxGetDoubles(out), carrier.data,
           mxGetNumberOfElements(out) * sizeof(double));
    jlw_release(carrier.data);
    return out;
}

static mxArray *jlw_out_int64_t(int64_t carrier)
{
    mxArray *out = mxCreateNumericMatrix(1, 1, mxINT64_CLASS, mxREAL);
    *mxGetInt64s(out) = carrier;
    return out;
}

static void jlw_call_bundle
    (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)prhs;
    int wanted = nlhs < 1 ? 1 : nlhs;
    if (wanted > 4) {
        mexErrMsgIdAndTxt("jlw:argument", "at most 4 outputs");
    }
    if (nrhs != 1) {
        mexErrMsgIdAndTxt("jlw:argument", "bundle takes 0 arguments");
    }
    JLWResult_CNTuple_4_Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64 result =
        ((JLWResult_CNTuple_4_Tuple_CString_owned_CStrArray_owned_CDict_owned_Float64_COpt_Float64 (*)(void))jlw_symbol("bundle"))();
    jlw_check(result.status);
    for (int64_t k = 0; k < result.value.values._3.length; k++) {
        if (!jlw_valid_field_name(result.value.values._3.keys[k].data, result.value.values._3.keys[k].length)) {
            jlw_release(result.value.values._1.data);
            jlw_release_strings(result.value.values._2.data, result.value.values._2.length);
            jlw_release_strings(result.value.values._3.keys, result.value.values._3.length);
            jlw_release(result.value.values._3.values);
            mexErrMsgIdAndTxt("jlw:argument",
                "a dictionary key is not a legal MATLAB field name");
        }
    }
    mxArray *out1 = jlw_out_CString_owned(result.value.values._1);
    mxArray *out2 = jlw_out_CStrArray_owned(result.value.values._2);
    mxArray *out3 = jlw_out_CDict_owned_Float64(result.value.values._3);
    mxArray *out4 = jlw_out_COpt_Float64(result.value.values._4);
    if (wanted >= 1) {
        plhs[0] = out1;
    } else {
        mxDestroyArray(out1);
    }
    if (wanted >= 2) {
        plhs[1] = out2;
    } else {
        mxDestroyArray(out2);
    }
    if (wanted >= 3) {
        plhs[2] = out3;
    } else {
        mxDestroyArray(out3);
    }
    if (wanted >= 4) {
        plhs[3] = out4;
    } else {
        mxDestroyArray(out4);
    }
}

static void jlw_call_pair
    (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)prhs;
    int wanted = nlhs < 1 ? 1 : nlhs;
    if (wanted > 2) {
        mexErrMsgIdAndTxt("jlw:argument", "at most 2 outputs");
    }
    if (nrhs != 1) {
        mexErrMsgIdAndTxt("jlw:argument", "pair takes 0 arguments");
    }
    JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_CVector_owned_Float64 result =
        ((JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_CVector_owned_Float64 (*)(void))jlw_symbol("pair"))();
    jlw_check(result.status);
    mxArray *out1 = jlw_out_CVector_owned_Float64(result.value.values[0]);
    mxArray *out2 = jlw_out_CVector_owned_Float64(result.value.values[1]);
    if (wanted >= 1) {
        plhs[0] = out1;
    } else {
        mxDestroyArray(out1);
    }
    if (wanted >= 2) {
        plhs[1] = out2;
    } else {
        mxDestroyArray(out2);
    }
}

static void jlw_call_stats
    (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)prhs;
    int wanted = nlhs < 1 ? 1 : nlhs;
    if (wanted > 2) {
        mexErrMsgIdAndTxt("jlw:argument", "at most 2 outputs");
    }
    if (nrhs != 1) {
        mexErrMsgIdAndTxt("jlw:argument", "stats takes 0 arguments");
    }
    JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_Int64 result =
        ((JLWResult_CNTuple_2_Tuple_CVector_owned_Float64_Int64 (*)(void))jlw_symbol("stats"))();
    jlw_check(result.status);
    mxArray *out1 = jlw_out_CVector_owned_Float64(result.value.values._1);
    mxArray *out2 = jlw_out_int64_t(result.value.values._2);
    if (wanted >= 1) {
        plhs[0] = out1;
    } else {
        mxDestroyArray(out1);
    }
    if (wanted >= 2) {
        plhs[1] = out2;
    } else {
        mxDestroyArray(out2);
    }
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    if (nrhs < 1 || !mxIsChar(prhs[0])) {
        mexErrMsgIdAndTxt("jlw:argument", "the first argument names the function");
    }
    char *name = mxArrayToUTF8String(prhs[0]);
    if (strcmp(name, "bundle") == 0) {
        jlw_call_bundle(nlhs, plhs, nrhs, prhs);
    } else if (strcmp(name, "pair") == 0) {
        jlw_call_pair(nlhs, plhs, nrhs, prhs);
    } else if (strcmp(name, "stats") == 0) {
        jlw_call_stats(nlhs, plhs, nrhs, prhs);
    } else {
        mexErrMsgIdAndTxt("jlw:argument", "unknown function %s", name);
    }
}
