"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libcdict"
_LIBRARY_ENV_VAR = "CDICT_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

class Nothing(ctypes.Structure):
    _fields_ = []

class CDict_Float64(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("keys", ctypes.POINTER(ctypes.POINTER(ctypes.c_uint8))),
        ("values", ctypes.POINTER(ctypes.c_double)),
    ]

    @classmethod
    def from_dict(cls, d):
        keys = [k.encode("utf-8") + b"\x00" for k in d.keys()]
        karr = (ctypes.POINTER(ctypes.c_uint8) * len(keys))(
            *[ctypes.cast(ctypes.create_string_buffer(b, len(b)), ctypes.POINTER(ctypes.c_uint8)) for b in keys])
        varr = (ctypes.c_double * len(keys))(*d.values())
        obj = cls(length=len(keys),
                  keys=ctypes.cast(karr, ctypes.POINTER(ctypes.POINTER(ctypes.c_uint8))),
                  values=ctypes.cast(varr, ctypes.POINTER(ctypes.c_double)))
        obj._buffer = (keys, karr, varr)
        return obj

    def as_dict(self):
        out = {}
        for i in range(self.length):
            k = ctypes.cast(self.keys[i], ctypes.c_char_p).value.decode("utf-8")
            out[k] = self.values[i]
        return out

_lib.take_dict.argtypes = [CDict_Float64]
_lib.take_dict.restype = ctypes.c_int64
def take_dict(d):
    return _lib.take_dict(d)

_lib.give_dict.argtypes = []
_lib.give_dict.restype = CDict_Float64
def give_dict():
    return _lib.give_dict()

_lib.jlw_free.argtypes = [ctypes.POINTER(Nothing)]
_lib.jlw_free.restype = None

_lib.jlw_free_strings.argtypes = [ctypes.POINTER(ctypes.POINTER(ctypes.c_uint8)), ctypes.c_int64]
_lib.jlw_free_strings.restype = None

