"""Auto-generated by JuliaLibWrapping. Do not edit by hand."""
import ctypes
import os
import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_LIBRARY_BASENAME = "libcstrarray"
_LIBRARY_ENV_VAR = "CSTRARRAY_DEMO_LIBRARY"

def _resolve_library_path():
    override = os.environ.get(_LIBRARY_ENV_VAR)
    if override:
        return override
    if sys.platform == "win32":
        suffixes = (".dll",)
    elif sys.platform == "darwin":
        suffixes = (".dylib", ".so")
    else:
        suffixes = (".so", ".dylib")
    tried = []
    for suffix in suffixes:
        candidate = _HERE / (_LIBRARY_BASENAME + suffix)
        tried.append(str(candidate))
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError(
        f"Could not locate shared library {_LIBRARY_BASENAME!r}. "
        f"Tried: {tried}. Set {_LIBRARY_ENV_VAR} to an explicit path."
    )

_lib = ctypes.CDLL(_resolve_library_path())

_JLW_LOADED_ATTR = "_jlw_loaded_packages"
_jlw_loaded = getattr(sys, _JLW_LOADED_ATTR, None)
if _jlw_loaded is None:
    _jlw_loaded = set()
    setattr(sys, _JLW_LOADED_ATTR, _jlw_loaded)
_jlw_this_pkg = __package__ or __name__
if _jlw_loaded and _jlw_this_pkg not in _jlw_loaded:
    import warnings
    warnings.warn(
        f"Loading JuliaLibWrapping-generated package {_jlw_this_pkg!r} into a "
        f"process that already loaded {sorted(_jlw_loaded)!r}. "
        "This package was built without a private libjulia, so both "
        "packages resolve a single Julia runtime and the first call into "
        "whichever did not initialize it aborts the process. Rebuild with "
        "`privatize = true`, or compile both APIs into a single juliac "
        "library. See the JuliaLibWrapping docs section on multiple "
        "wrapped libraries in one process.",
        RuntimeWarning,
        stacklevel=2,
    )
_jlw_loaded.add(_jlw_this_pkg)

class Nothing(ctypes.Structure):
    _fields_ = []

class CString(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_uint8)),
    ]

    @classmethod
    def from_str(cls, s):
        """Return a CString whose buffer holds the UTF-8 encoding of `s`.

        Allocates a fresh ctypes buffer and copies the bytes into it; the
        returned object holds a reference to that buffer, so the caller
        must keep it alive for the duration of any C call that uses it."""
        if not isinstance(s, str):
            raise TypeError(f"expected str, got {type(s).__name__}")
        return cls.from_bytes(s.encode("utf-8"))

    @classmethod
    def from_bytes(cls, b):
        """Return a CString whose buffer holds a copy of the bytes `b`."""
        if not isinstance(b, (bytes, bytearray)):
            raise TypeError(f"expected bytes-like, got {type(b).__name__}")
        n = len(b)
        buf = (ctypes.c_uint8 * n).from_buffer_copy(b) if n else (ctypes.c_uint8 * 0)()
        obj = cls(length=n,
                  data=ctypes.cast(buf, ctypes.POINTER(ctypes.c_uint8)))
        obj._buffer = buf
        return obj

    def as_bytes(self):
        """Return a copy of the underlying bytes as a Python `bytes` object."""
        return ctypes.string_at(self.data, self.length)

    def as_str(self):
        """Return the underlying bytes decoded as UTF-8."""
        return self.as_bytes().decode("utf-8")

class CStrArray(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int64),
        ("data", ctypes.POINTER(CString)),
        ("owned", ctypes.c_int32),
    ]

    @classmethod
    def from_list(cls, items):
        if not isinstance(items, (list, tuple)):
            raise TypeError("expected a list of str")
        bufs = [s.encode("utf-8") for s in items]
        arr = (CString * len(bufs))(
            *[CString(length=len(b), data=ctypes.cast(ctypes.create_string_buffer(b, len(b)), ctypes.POINTER(ctypes.c_uint8))) for b in bufs])
        obj = cls(length=len(bufs), data=ctypes.cast(arr, ctypes.POINTER(CString)), owned=0)
        obj._buffer = (bufs, arr)   # keepalive — the from_numpy pattern
        return obj

    def as_list(self):
        out = []
        for i in range(self.length):
            e = self.data[i]
            out.append(ctypes.string_at(e.data, e.length).decode("utf-8"))
        return out

    def free(self):
        """Free the Julia-allocated buffer iff this object owns it (owned is 1).

        Idempotent: a second call, or a call on a borrowed (owned is 0) value, is a
        no-op. For callers who bypass the façade's convert-then-free wrapper and
        talk to `_lowlevel` directly."""
        if self.owned != 1:
            return
        _lib.jlw_free_strings(self.data, self.length)
        self.owned = 0

_lib.take_strs.argtypes = [CStrArray]
_lib.take_strs.restype = ctypes.c_int64
def take_strs(a):
    return _lib.take_strs(a)

_lib.give_strs.argtypes = []
_lib.give_strs.restype = CStrArray
def give_strs():
    return _lib.give_strs()

_lib.jlw_free.argtypes = [ctypes.c_void_p]
_lib.jlw_free.restype = None

_lib.jlw_free_strings.argtypes = [ctypes.POINTER(CString), ctypes.c_int64]
_lib.jlw_free_strings.restype = None

