/* Auto-generated by JuliaLibWrapping. Do not edit by hand. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <dlfcn.h>
#include <fcntl.h>
#endif
#include "mex.h"
#include "libdemo_mex_types.h"

/* Where the shared library is. `build_mex.m` bakes in the path it
   was built against; the environment variable overrides it. A bare
   name resolves against MATLAB's working directory, not the MEX
   file's location. */
#ifndef JLW_LIBRARY_PATH
#define JLW_LIBRARY_PATH "libdemo"
#endif
#define JLW_LIBRARY_ENV "LIBDEMO_MEX_LIBRARY"

static void *jlw_library = NULL;

/* Julia's runtime marks inherited pipes non-blocking and leaves
   them that way, which MATLAB's own reads then see as errors.
   It bites when MATLAB runs under -batch in a pipeline. */
typedef struct { int ok; int flags[3]; } jlw_stdio_flags;

static jlw_stdio_flags jlw_save_stdio(void)
{
    jlw_stdio_flags saved;
    saved.ok = 0;
#ifndef _WIN32
    for (int fd = 0; fd < 3; fd++) {
        saved.flags[fd] = fcntl(fd, F_GETFL);
    }
    saved.ok = 1;
#endif
    return saved;
}

static void jlw_restore_stdio(jlw_stdio_flags saved)
{
#ifndef _WIN32
    if (saved.ok) {
        for (int fd = 0; fd < 3; fd++) {
            if (saved.flags[fd] != -1) {
                fcntl(fd, F_SETFL, saved.flags[fd]);
            }
        }
    }
#else
    (void)saved;
#endif
}

/* Opened once and never closed: `clear mex` unloads this file, and
   reloading the library would run `jl_init` twice in one process. */
static void *jlw_symbol(const char *name)
{
    if (jlw_library == NULL) {
        const char *override = getenv(JLW_LIBRARY_ENV);
        jlw_stdio_flags saved = jlw_save_stdio();
        char path[4096];
        const char *base = override ? override : JLW_LIBRARY_PATH;
        char reason[256];
#ifdef _WIN32
        snprintf(path, sizeof path, "%s.dll", base);
        /* ALTERED_SEARCH_PATH so the library's own directory is
           searched for its dependencies, libjulia among them. */
        jlw_library = (void *)LoadLibraryExA(path, NULL,
                                            LOAD_WITH_ALTERED_SEARCH_PATH);
        snprintf(reason, sizeof reason, "error %lu",
                 (unsigned long)GetLastError());
#else
#ifdef __APPLE__
        snprintf(path, sizeof path, "%s.dylib", base);
#else
        snprintf(path, sizeof path, "%s.so", base);
#endif
        jlw_library = dlopen(path, RTLD_LAZY | RTLD_GLOBAL | RTLD_NODELETE);
        const char *message = dlerror();
        snprintf(reason, sizeof reason, "%s", message ? message : "");
#endif
        if (jlw_library == NULL) {
            mexErrMsgIdAndTxt("jlw:library",
                "could not load %s (%s); set " JLW_LIBRARY_ENV
                " to its path without the extension", path, reason);
        }
        jlw_restore_stdio(saved);
    }
#ifdef _WIN32
    void *address = (void *)GetProcAddress((HMODULE)jlw_library, name);
#else
    void *address = dlsym(jlw_library, name);
#endif
    if (address == NULL) {
        mexErrMsgIdAndTxt("jlw:library", "missing entry point %s", name);
    }
    return address;
}


static int jlw_valid_field_name(const uint8_t *data, int32_t n)
{
    if (n <= 0 || n >= mxMAXNAM) {
        return 0;
    }
    for (int32_t j = 0; j < n; j++) {
        uint8_t c = data[j];
        int alpha = (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z');
        int rest = (c >= '0' && c <= '9') || c == '_';
        /* A field name starts with a letter. */
        if (!(j == 0 ? alpha : (alpha || rest))) {
            return 0;
        }
    }
    return 1;
}

static void jlw_release(void *pointer)
{
    static void (*entry)(void *) = NULL;
    if (entry == NULL) {
        entry = (void (*)(void *))jlw_symbol("jlw_free");
    }
    entry(pointer);
}

static void jlw_release_strings(void *items, int64_t count)
{
    static void (*entry)(void *, int64_t) = NULL;
    if (entry == NULL) {
        entry = (void (*)(void *, int64_t))jlw_symbol("jlw_free_strings");
    }
    entry(items, count);
}

static CDict_borrowed_Float64 jlw_in_CDict_borrowed_Float64(const mxArray *value)
{
    int count = mxGetNumberOfFields(value);
    CString_borrowed *keys =
        (CString_borrowed *)mxMalloc((count ? count : 1) * sizeof(CString_borrowed));
    double *values =
        (double *)mxMalloc((count ? count : 1) * sizeof(double));
    for (int i = 0; i < count; i++) {
        const char *key = mxGetFieldNameByNumber(value, i);
        keys[i].length = (int32_t)strlen(key);
        /* A MATLAB field name is at most `mxMAXNAM`, so it fits. */
        keys[i].data = (uint8_t *)key;
        const mxArray *field = mxGetFieldByNumber(value, 0, i);
        /* A sparse field passes a class check and has no
           dense buffer to read. */
        if (field == NULL || mxIsSparse(field) ||
            !mxIsDouble(field) ||
            mxGetNumberOfElements(field) != 1) {
            mexErrMsgIdAndTxt("jlw:argument",
                "field %s must be a double scalar", key);
        }
        values[i] = *mxGetDoubles(field);
    }
    CDict_borrowed_Float64 carrier;
    carrier.length = (int64_t)count;
    carrier.keys = keys;
    carrier.values = values;
    return carrier;
}

static mxArray *jlw_out_CDict_owned_Float64(CDict_owned_Float64 carrier)
{
    /* Keys are checked before anything is created, so a bad
       one is reported while nothing is held. */
    for (int64_t i = 0; i < carrier.length; i++) {
        if (!jlw_valid_field_name(carrier.keys[i].data, carrier.keys[i].length)) {
            jlw_release_strings(carrier.keys, carrier.length);
            jlw_release(carrier.values);
            mexErrMsgIdAndTxt("jlw:argument",
                "a dictionary key is not a legal MATLAB field name");
        }
    }
    const char **names =
        (const char **)mxMalloc((size_t)(carrier.length ? carrier.length : 1) * sizeof(char *));
    for (int64_t i = 0; i < carrier.length; i++) {
        char *key = (char *)mxMalloc((size_t)carrier.keys[i].length + 1);
        memcpy(key, carrier.keys[i].data, (size_t)carrier.keys[i].length);
        key[carrier.keys[i].length] = '\0';
        names[i] = key;
    }
    mxArray *out = mxCreateStructMatrix(1, 1, (int)carrier.length, names);
    for (int64_t i = 0; i < carrier.length; i++) {
        mxArray *field = mxCreateNumericMatrix(1, 1, mxDOUBLE_CLASS, mxREAL);
        *mxGetDoubles(field) = (double)carrier.values[i];
        mxSetFieldByNumber(out, 0, (int)i, field);
    }
    jlw_release_strings(carrier.keys, carrier.length);
    jlw_release(carrier.values);
    return out;
}

static mxArray *jlw_out_int64_t(int64_t carrier)
{
    mxArray *out = mxCreateNumericMatrix(1, 1, mxINT64_CLASS, mxREAL);
    *mxGetInt64s(out) = carrier;
    return out;
}

static void jlw_call_give_dict
    (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs;
    (void)prhs;
    if (nrhs != 1) {
        mexErrMsgIdAndTxt("jlw:argument", "give_dict takes 0 arguments");
    }
    CDict_owned_Float64 result =
        ((CDict_owned_Float64 (*)(void))jlw_symbol("give_dict"))();
    plhs[0] = jlw_out_CDict_owned_Float64(result);
}

static void jlw_call_take_dict
    (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    (void)nlhs;
    if (nrhs != 2) {
        mexErrMsgIdAndTxt("jlw:argument", "take_dict takes 1 arguments");
    }
    if (mxIsSparse(prhs[1])) {
        mexErrMsgIdAndTxt("jlw:argument", "d must not be sparse");
    }
    if (!mxIsStruct(prhs[1])) {
        mexErrMsgIdAndTxt("jlw:argument", "d must be a struct");
    }
    CDict_borrowed_Float64 arg1 = jlw_in_CDict_borrowed_Float64(prhs[1]);
    int64_t result =
        ((int64_t (*)(CDict_borrowed_Float64))jlw_symbol("take_dict"))(arg1);
    plhs[0] = jlw_out_int64_t(result);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    if (nrhs < 1 || !mxIsChar(prhs[0])) {
        mexErrMsgIdAndTxt("jlw:argument", "the first argument names the function");
    }
    char *name = mxArrayToUTF8String(prhs[0]);
    if (strcmp(name, "give_dict") == 0) {
        jlw_call_give_dict(nlhs, plhs, nrhs, prhs);
    } else if (strcmp(name, "take_dict") == 0) {
        jlw_call_take_dict(nlhs, plhs, nrhs, prhs);
    } else {
        mexErrMsgIdAndTxt("jlw:argument", "unknown function %s", name);
    }
}
